### ISSUE TITLE
Relicensing to MIT

### ISSUE THREAD

**Issue by antonioribeiro** [antonioribeiro/google2fa#100]
Dear contributors,

To allow this package to be adopted by other projects, I'm trying to move the license of this package from the original [GPLv3](https://www.idontplaydarts.com/static/ga.php_.txt) to something more permissive, like MIT, but I need **you** and the original developer (Phil), to approve it.

So, I'm listing all of you (up to today) and ask for a YAY/NAY comment in this thread, from each one of you.

If you have any questions or something to say about this change, please do. 

If you have a really good understanding of licensing (which I do not), please jump in and help us.

- [x] Phil - phil [at] xqi [dot] cc
- [x] @antonioribeiro
- [x] @barryvdh
- [x] @GrahamCampbell
- [x] @SebastianS90
- [x] @aik099
- [ ] @medinae
- [x] @taichunmin
- [x] @jbrooksuk
- [x] @drbyte
- [x] @mikerockett
- [ ] @zhiyi7
- [ ] @PixellUp
- [ ] @bram1028
- [x] @proshanto
- [ ] @cnanney
- [x] @ashnewmanjones
- [ ] @kalfheim
- [x] @it-can
- [x] @tshafer
- [x] @adeelx
- [x] @ngyikp
- [x] @domodwyer
- [x] @leandro-lugaresi

**Comment by barryvdh** [comment]
Yay

**Comment by SebastianS90** [comment]
Fine for me!

**Comment by domodwyer** [comment]
Absolutely!

**Comment by it-can** [comment]
Yup

**Comment by antonioribeiro** [comment]
Just got Phil's blessing

![image](https://user-images.githubusercontent.com/3182864/37431678-aa4d9bce-27b4-11e8-9307-33d75a31ab7a.png)

**Comment by adeelx** [comment]
Yay

**Comment by drbyte** [comment]
Yay

**Comment by ngyikp** [comment]
Yay

**Comment by tshafer** [comment]
Yay

**Comment by taichunmin** [comment]
YAY

**Comment by proshanto** [comment]
YAY




Regards,
Proshanta Barman

**Comment by mikerockett** [comment]
Couldn't agree more! 👍

**Comment by ashnewmanjones** [comment]
YAY

**Comment by jbrooksuk** [comment]
Sure!

**Comment by antonioribeiro** [comment]
Yes!

**Comment by leandro-lugaresi** [comment]
:+1:

**Comment by antonioribeiro** [comment]
We need at least 95% of all contributors/contributions to make this change, but we have only, so if @GrahamCampbell gives us his AYE, we should be good to go:

![image](https://user-images.githubusercontent.com/3182864/37478578-5aa2d378-2859-11e8-937a-fe4322734e2f.png)

**Comment by aik099** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Do whatever you want. I don't mind. :)

**Comment by antonioribeiro** [comment]
With 98%+ of contributions/contributors, I'm considering this proposal as approved, but still hoping to reach 100%.

![image](https://user-images.githubusercontent.com/3182864/37495161-d35565de-288a-11e8-9412-d84aa59efb88.png)
