### ISSUE TITLE
BaconQrCode New Version Class Not Found

### ISSUE THREAD

**Issue by lkloon123** [antonioribeiro/google2fa#105]
`Class 'BaconQrCode\Renderer\Image\Png' not found`

due to changes in BaconQrCode 2.0

**Comment by thedotedge** [comment]
v2.0 doesn't include the PNG renderer:

`composer require bacon/bacon-qr-code 1.0.3`

**Comment by mrzeta** [comment]
if u want use new baconqrcode  
1： change qrcode.php 
// use BaconQrCode\Renderer\Image\Png;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\ImagickImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
2：modify getQRCodeInline function
        // $renderer = new Png();
        // $renderer->setWidth($size);
        // $renderer->setHeight($size);

        $renderer = new ImageRenderer(
            new RendererStyle(200),
            new ImagickImageBackEnd()
        );
enjoy it~~

**Comment by thedotedge** [comment]
@mrzeta will you add this in PR? :)

**Comment by robertnicjoo** [comment]
@mrzeta  i get

```
You need to install the imagick extension to use this back end
```

**Comment by antonioribeiro** [comment]
Extracted to a new package: https://github.com/antonioribeiro/google2fa-qrcode
