### ISSUE TITLE
Google Infographics QR Code API is deprecated

### ISSUE THREAD

**Issue by bdteo** [antonioribeiro/google2fa#107]
See: https://developers.google.com/chart/infographics/docs/qr_codes

**Comment by Chevil5** [comment]
Hi, is there any updates about that? 5 days ago Google turned off QR code generator api. And now it does not work at all.

**Comment by barryvdh** [comment]
I can confirm that currently:
 - Google Chart API is offline, so URL doesn't work
 - Bacon 2.x is released a year ago and doesn't work with this package.

**Comment by antonioribeiro** [comment]
Why Bacon doesn't work with it? When I removed it from this package to create the google2fa-bridge I tested it with both 1.x and 2.x...

**Comment by barryvdh** [comment]
Oh sorry, I'm still on the 2.x branch.
I just saw your qr code package, but you don't mention it in the readme, right? 
https://github.com/antonioribeiro/google2fa#qr-code-packages

An alternative would be to use http://goqr.me/api/ but I think it would probably best to not provide external API for this sensitive stuff.

**Comment by antonioribeiro** [comment]
With Bacon 2.0:

```
    $google2fa = app(Google2FA::class);

    $url = $google2fa->getQRCodeUrl(
        'pragmarx',
        'google2fa@pragmarx.com',
        $google2fa->generateSecretKey()
    );

    $writer = new Writer(
        new ImageRenderer(
            new RendererStyle(400),
            new ImagickImageBackEnd()
        )
    );

    $writer->writeFile($url, 'qrcode.png');

    // or

    dd($writer->writeString($url));
```

**Comment by barryvdh** [comment]
Thanks, I've updated generate the QR with https://github.com/endroid/qr-code

```php
function qrCodeUrl($value, $size = 200)
{
    $qrCode = new \Endroid\QrCode\QrCode($value);

    $qrCode->setSize($size);

    return $qrCode->writeDataUri();
}
```

But should we remove the Google API?

**Comment by antonioribeiro** [comment]
> Oh sorry, I'm still on the 2.x branch.
> I just saw your qr code package, but you don't mention it in the readme, right?
> https://github.com/antonioribeiro/google2fa#qr-code-packages
> 
> An alternative would be to use http://goqr.me/api/ but I think it would probably best to not provide external API for this sensitive stuff.

Yeah, sorry, I wasn't really sure about "tying" one more package to this stack. But I will update the README and add some examples using it (mine), Bacon and Endroid.

**Comment by antonioribeiro** [comment]
> But should we remove the Google API?

Yes, we must.

And thanks a lot for the Endroid fix!

**Comment by antonioribeiro** [comment]
That Google API was deprecated in favor of https://developers.google.com/chart/, but I'm not sure there is a QRCode API inside it, will have to look better.

**Comment by antonioribeiro** [comment]
Thanks for that PR.

Will try to add some more examples later.

**Comment by barryvdh** [comment]
I don't think it supports QR code. So we can either:
 - Deprecate it and leave it in as not working, remove in next version (but will be broken and many won't notice)
 - Throw an Exception to make it clear what is happening (breaking, but it's already broken)
 - Replace with different API (but insecure)
 - Silently replace with an data URL (eg. with bacon), not the same but doesn't break (but could lead to dependancy conflicts)

**Comment by Chevil5** [comment]
-Silently replace with an data URL (eg. with bacon)
this option looks the most effective. The tool is very useful and it would be cruel just leave it unworking. Really people do not care how QR code generates, but only it should be secure, so to make in in-place by using Bacon would be perfect in my opinion.

**Comment by antonioribeiro** [comment]
I was working on removing it for 5.0.0, already pushed some code to it, but looks like we will have to think this better. 

I'm not found of adding Bacon or any other dependency back to this package, but if we do, to get a "fixed" version people would have to `composer update`, so here's a question:

Is there a way to make Composer warn people and tell them to upgrade to 5.0.0 and check the docs for options?

**Comment by Chevil5** [comment]
As far as I can see - no. And googling did not give any results. 

But as a user, I can say it would be clear for me what is going on if on the first line of the documentation we will write: "Google API for QR generation is turned off. All version of that package less than 5.0.0 is deprecated and non-working. Please, make `composer update` and check documentation regarding new generation QR logic". 
In a few days, people will see that QR code is broken and will start googling or checking the documentation. And way they will find this information.

**Comment by barryvdh** [comment]
An alternative would be to patch to previous version(s) to a hardcoded data url, with a message so it's more of a Soft fail.

**Comment by antonioribeiro** [comment]
> As far as I can see - no. And googling did not give any results.
> 
> But as a user, I can say it would be clear for me what is going on if on the first line of the documentation we will write: "Google API for QR generator is turned off. All version of that package less than 5.0.0 is deprecated and non-working. Please, make `composer update` and check documentation regarding new generation QR logic".
> In a few days, people will see that QR code is broken and will start googling or checking the documentation. And way they will find this information.

Done:

![image](https://user-images.githubusercontent.com/3182864/54640123-c9db6480-4a6d-11e9-8424-bafed069c984.png)

**Comment by antonioribeiro** [comment]
What about this?:

![image](https://user-images.githubusercontent.com/3182864/54647876-f51c7e80-4a82-11e9-8696-4bcd721f9be4.png)

As a warning when people `composer update`?

**Comment by antonioribeiro** [comment]
It's done, but not working. Not sure why

https://github.com/Ocramius/PackageVersions/blob/master/composer.json

works, but this one doesn't:

https://github.com/antonioribeiro/google2fa/blob/v4.0.2/composer.json

**Comment by Chevil5** [comment]
> Done:

 @antonioribeiro thank you! Looks super noticeable and understandable! I also checked fixed documentation it looks very clear. I already fixed my code by your recommendations with Bacon and it works like a charm. So thank you for your work! 

Warning in console looks also very good. But I'm not sure how to force it to work. It looks correct as far I can see.

**Comment by antonioribeiro** [comment]
Opened an issue in Composer to try to understand and fix it: https://github.com/composer/composer/issues/8049

**Comment by hopeseekr** [comment]
There is a way to immediately warn people... But it's not that good.

1. Edit this package's composer.json and give it either a new name or a new vendor, or both.
2. Mark this current package on packagist as abandoned. 
3. Add as a Recommendation the new package name.

Then, any time anyone does `composer install` or `composer update`, they'll get a big red warning `google2fa is abandoned: Use google-2fa instead.`.
