### ISSUE TITLE
There is no getQRCodeInline in QRCode.php

### ISSUE THREAD

**Issue by pndx** [antonioribeiro/google2fa#111]
how can i generate a qrcode image? What should i do?

**Comment by antonioribeiro** [comment]
In the latest major version this logic was moved to another package: 
https://github.com/antonioribeiro/google2fa-qrcode

**Comment by pndx** [comment]
Thanks for the reply. I solved the problem.

**Comment by Patrickstek121** [comment]
Please update documentation...
