### ISSUE TITLE
Authenticator is always returning true for ::isAuthenticated()

### ISSUE THREAD

**Issue by VerheijenWebdevelopment** [antonioribeiro/google2fa#112]
I'm trying to implement your package and so far saving secrets and verifying codes is working great. But I want to use my own middleware and the following code always returns true (placed in a controller for debugging purposes, but same effect in my middleware).
```
$authenticator = app(Authenticator::class)->boot($request);
$authenticator->logout();
Google2FA::logout();
dd($authenticator->isAuthenticated(), $request);
```

Anything I could be missing? If you need more information please ask, not sure what else to tell you.

**Comment by Datalink-Wouter** [comment]
Do you know how to solve this? 
I got the same thing.
Thanks
