### ISSUE TITLE
Problems on production

### ISSUE THREAD

**Issue by maurocasas** [antonioribeiro/google2fa#12]
I've been using this package in many projects now, and it's really strange that in the current one I'm on, when I push to production, the tokens are invalidated, though the secret and token are being sent properly.

Is there any known "tip" or something we should know of?

Thanks!

**Comment by maurocasas** [comment]
I have fixed this issue. 

It was due to the timezone of the server. It's really important to keep it sync with ntp.ubuntu.com

**Comment by bjornpost** [comment]
I'm also having issues, but on my development machine. This is what I'm seeing. If I hard code the code, timestamps and secrets:

    $google2FA->verifyKey('ADUMJO5634NPDEKW', '410272', 4, 26213400);
    // => true
    $google2FA->verifyKey('ZU52HWXMZOKDDYUE', '889144', 4, 1444155370);
    // => false, should be one of 133892 | 552514 | 499078 | 611978
    // according to the google2fa (889144 is the code generated by the iOS app)

Secrets generated via Google Authenticator are never accepted. Even increasing the window from 4 to 86400 seconds (= a day), does not fix the issue. I guess that crosses a time sync issue off the list. What to check next?
