### ISSUE TITLE
Compatibility problem with PHP < 7

### ISSUE THREAD

**Issue by aletede21** [antonioribeiro/google2fa#127]
In the file Base32.php row 75 there is a return type that is not provided in PHP < 7

**Comment by antonioribeiro** [comment]
Yeah, it's hard to keep supporting older versions of PHP.

**Comment by antonioribeiro** [comment]
New version should work on 7.0, removed those type hints, but I cannot rally test it on 7.0, because of: https://travis-ci.org/antonioribeiro/google2fa/jobs/588587454.

If you find a nice way to keep tests running on PHP<7.1, I can bring support back to it, but for now I will change it to PHP>=7.1.

**Comment by GrahamCampbell** [comment]
This issue can be closed now.
