### ISSUE TITLE
Suggestion - stricter returns

### ISSUE THREAD

**Issue by Khyber3737** [antonioribeiro/google2fa#130]
Just some food for thought!

Wouldn't make more sense to avoid mixed returns? E.g. bool|int when using verifyKey

And is this correct? https://github.com/antonioribeiro/google2fa/blob/master/src/Google2FA.php#L54 (int $startingTimestamp)

I found it when phpstan was giving me a lot of errors because I was treating verifyKey as return bool.

**Comment by antonioribeiro** [comment]
Should be fixed in 6.1.1. @Khyber3737 would you mind testing it again and closing this?

Thanks for reporting!

**Comment by Khyber3737** [comment]
I have verified that with `--level 4` there are no errors. With `--level max` I get the usual errors that, from a library standpoint (not targeting >= 7.4, strict), makes perfect sense since it's just casting/coersion or a design decision. In hindsight since this library is used everywhere and is battle tested it would be difficult to change methods like findValidOTP and verifyKey. I will deal with that in a more proper opinionated layer.
Thank you! :)

**Comment by antonioribeiro** [comment]
Yeah, I tested it with level 4, sorry. I'm not really a PHPStan user, so I didn't know there were levels above it :/

**Comment by antonioribeiro** [comment]
@Khyber3737 Would you please test 6.1.2, please? I think I managed to make them all pass. I had to make one change in code, but it should not break things. It doesn't make sense let people pass $secret as null here:

![image](https://user-images.githubusercontent.com/3182864/67227464-af0b0d00-f40d-11e9-8090-7ab29e12d049.png)

**Comment by Khyber3737** [comment]
>[OK] No errors

👍

**Comment by antonioribeiro** [comment]
It's now on 7.0.0. I ended up causing a BC break, so I had to roll them back and draft a new major release.
