### ISSUE TITLE
Null values on verifyKeyNewer regression

### ISSUE THREAD

**Issue by williamhector** [antonioribeiro/google2fa#134]
When a user account is logging in for the first time and they don't yet have an old timestamp to provide to `verifyKeyNewer`, calling it doesn't get a new timestamp returned for next time either, only a `true` value.

This seems to have been previously addressed in #70 and 592ca6f021b950b2eb39a05ed33913613888d66d and then regressed in ffdcb8231d0a19d0cda9b188e799dd6b8d9014db with the change back to using `is_null($oldTimestamp)` in `findValidOTP`.

Current workaround for me is to check if the result of `verifyKeyNewer` is `true` and if so, set the user's 2fa timestamp to the result of `getTimestamp`.

**Comment by antonioribeiro** [comment]
@williamhector, this is actually the behavior of `findValidOTP`, since forever: 

https://github.com/antonioribeiro/google2fa/blob/8.x/src/Google2FA.php#L83
