### ISSUE TITLE
Google MFA without QR code ?

### ISSUE THREAD

**Issue by akamarvin** [antonioribeiro/google2fa#154]
Is this even possible ?
For me the QR code is a major no go. it's a thing from the past.
Can't it be like MS authenticator ? with just a one time passcode or even better, just an approval inside a notification you receive in Android ?

Please tell me if these are possible with your lib or are indeed not possible ever with the way google mfa is done. 
or with Authy maybe ?

**Comment by VeganDude** [comment]
If you don't want to scan the QR code, you can just manually enter the secret generated, this works with Authy

**Comment by akamarvin** [comment]
Sorry , the question was a bit off topic, just because I'm used to MS Azure MFA, with the approval directly in the notification you receive on your Android device, which I find much simpler. 
No need to scan anything.

**Comment by RobertBoes** [comment]
This package provides TOTP authentication, the protocol works like this. Microsoft seems to use their own implementation, which provides the push notifications. You can still use TOTP 2FA in the Microsoft Authenticator, but that also works by scanning a QR code and manually typing the token.
I think what you're looking for is something like Authy, by using their app and API you can send a push notification, Authy OneTouch it's called. You can take a look at [twilio/authy-php](https://github.com/twilio/authy-php), maybe that suits your needs better than TOTP
