### ISSUE TITLE
v8 changelog

### ISSUE THREAD

**Issue by niektenhoopen** [antonioribeiro/google2fa#155]
What has been changed in the v8.0.0 version? There is nothing in the changelog

**Comment by antonioribeiro** [comment]
Not much, a lot of cleanup, added more tests, some refactoring, PHP 8 support, but we changed some interfaces and because of that I bumped the major to 8, just to be on a safe spot.

**Comment by antonioribeiro** [comment]
CHANGELOG.md has some information

**Comment by antonioribeiro** [comment]
Oh! Also: PHP version bumped to >= 7.1
Another reason to bump the version to 8.0
