### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST

### ISSUE THREAD

**Issue by mvdgeijn** [antonioribeiro/google2fa#156]
Hi,

I don't know if this is a misconfiguration, or a bug, but I'm getting the error "The GET method is not supported for this route. Supported methods: POST" when I enter the MFA code wrong, and after that enter the right code. On entering the correct code the second time, the error appears.

When entering the correct code the first time, no problem occurs and everything runs as expected.

I'm not sure what code I should add to this question, but I can post relevant parts when needed.

Thanks!

**Comment by Snakzi** [comment]
Did you solve your issue? I have the exact same.

**Comment by MarkTatterTierney** [comment]
`Route::post('2fa', function () {
    return redirect(route('asset.index')); // Default 'home' page after login.
})->name('2fa')->middleware('2fa');`

I had the same issue so Instead of having a redirect to previous URL I changed it to a default home page or dashboard redirect. Seemed to fix the issue.

**Comment by mvdgeijn** [comment]
Thanks @MarkTatterTierney, I also fixed this using simular code.
