### ISSUE TITLE
Valid is always false

### ISSUE THREAD

**Issue by sidclaynt** [antonioribeiro/google2fa#157]
i'm trying to enable 2fa but i get $valid as false all the time. what is missing?

`$google2FA = new Google2FA();
        $request->verifyCode = "VFRXCICGWNUBMBHU";
	//dd($google2FA);
	$secret = $request->verifyCode;
	
	$valid = $google2FA->verifyKey($user->passwordSecurity->google2fa_secret, $secret);
`        echo $valid; //false

**Comment by ajeetimpelysm** [comment]
Ya got the same issues.
