### ISSUE TITLE
Get the TOTP to send through SMS

### ISSUE THREAD

**Issue by davincileon** [antonioribeiro/google2fa#159]
Hi, the library is amazing. Is there some way, in case of the user doesn't have any authenticator app, to generate a valid TOPT to be sent via SMS ?
thanks in advance.

**Comment by antonioribeiro** [comment]
You can probably use the `$google2fa->getCurrentOtp($secret)` method to get the current OTP (one time password), but it lives only 30 seconds, so you better increase your window or your users will never have enough time to receive and type it.
