### ISSUE TITLE
Call to undefined method PragmaRX\Google2FA\Google2FA::getQRCodeInline()

### ISSUE THREAD

**Issue by Saqib-QA** [antonioribeiro/google2fa#162]
I just installed this package on my local, using Laravel 7.28.3 
followed the steps described at [https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/](https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/) and got the following error.
Error
Call to undefined method PragmaRX\Google2FA\Google2FA::getQRCodeInline()
rechecked my code with repo, code is fine.

**Comment by Saqib-QA** [comment]
sorry

**Comment by mfn** [comment]
I think you created this on the wrong repo, I think this should be at https://github.com/antonioribeiro/google2fa-laravel (but it's easy to miss this I guess)

> PragmaRX\Google2FA\Google2FA::getQRCodeInline()

This is supposed to reference the Facade alias, see https://github.com/antonioribeiro/google2fa-laravel#use-the-facade

HTH

**Comment by antonioribeiro** [comment]
Yeah, @mfn, got it right, @Saqib-QA , just follow examples on our readme, and you should be fine.
