### ISSUE TITLE
feature request: using qrcodejs to remove dependency simplesoftwareio/simple-qrcode

### ISSUE THREAD

**Issue by ryh** [antonioribeiro/google2fa#17]
feature request: using `qrcodejs` to remove dependency `simplesoftwareio/simple-qrcode`

show QRCode is a front-end need, so it is reasonable to achieve it in `Client Side` with javascript.
[qrcodejs](https://github.com/davidshimjs/qrcodejs) is a perfect solution  for this.
(leave the show QRCode task to the front-end guy :jack_o_lantern: )
ext-gd and simplesoftwareio/simple-qrcode are *heavy* dependency for 2fa server side package

**Comment by antonioribeiro** [comment]
I can do that.

Is everyone okay with removing it?

**Comment by nathanmac** [comment]
:+1:

**Comment by cpwc** [comment]
:+1:

**Comment by override-chaos** [comment]
:+1:

**Comment by vinicius73** [comment]
:+1:

**Comment by aik099** [comment]
The dependency can be moved to `suggest` part in `composer.json`. Then in places, where library is used the exception can be thrown, when dependency isn't installed.

**Comment by it-can** [comment]
👍

**Comment by aik099** [comment]
Anyone doing 👍  are welcome to send a PR as well.

**Comment by barryvdh** [comment]
The dependency is a little bit less heavy now with #36, but you could still submit a PR if you need.

**Comment by antonioribeiro** [comment]
Moved to suggest. I will probably tag 1.0 soon, as this is a breaking change. 

I could tag it 0.9, but it would not break **only** if people is requiring `^0.8`, instead of `~0.8`. 

So, should I still tag a minor?

**Comment by GrahamCampbell** [comment]
People who have `~0.8` would expect it to be broken. They are doing that knowing that it could break. I'd say just break it in 0.9.0.

**Comment by antonioribeiro** [comment]
Whoops! Just tagged it 1.0.0 :/

**Comment by antonioribeiro** [comment]
Not everyone knows the difference between ~ and ^ on composer when the major version == 0. I myself had  some pain with it a while ago.

**Comment by barryvdh** [comment]
If they don't know the difference, they should just use `0.8.x` ;) But this is fine too :)
