### ISSUE TITLE
composer error: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)     Unzip with 7z command failed, falling back to ZipArchive class

### ISSUE THREAD

**Issue by PVI-Bat** [antonioribeiro/google2fa#183]
Under Windows 10, I try to install with composer require bacon/bacon-qr-code but get this error: 

C:\inst>composer require bacon/bacon-qr-code
Using version ^2.0 for bacon/bacon-qr-code
./composer.json has been created
Running composer update bacon/bacon-qr-code
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking bacon/bacon-qr-code (2.0.8)
  - Locking dasprid/enum (1.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing dasprid/enum (1.0.3): Extracting archive
  - Installing bacon/bacon-qr-code (2.0.8): Extracting archive
 0/2 [>---------------------------]   0%    Failed to extract dasprid/enum: (7) D:\Lua\5.1\7z.EXE x -bb0 -y C:\inst\vendor\composer\tmp-00ee02c8f4af9f85331dd569cf5cc4fb -oC:\inst\vendor\composer\ef3967dc

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with 7z command failed, falling back to ZipArchive class
    Failed to extract bacon/bacon-qr-code: (7) D:\Lua\5.1\7z.EXE x -bb0 -y C:\inst\vendor\composer\tmp-657cd265e68422b530a8a1796bfb8cdf -oC:\inst\vendor\composer\a6e8c1f9

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with 7z command failed, falling back to ZipArchive class
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
No security vulnerability advisories found

**Comment by antonioribeiro** [comment]
You probably need to check this problem with Bacon. Sorry.
