### ISSUE TITLE
verifyKeyNewer

### ISSUE THREAD

**Issue by roelfilweb** [antonioribeiro/google2fa#189]
How exactly to used "verifyKeyNewer" I always getting a "false" value on my timestamp when using this:

 $timestamp = $google2fa->verifyKeyNewer($this->google2fa, $password, $this->google2fa_ts);

var_dump($timestamp);

**Comment by George2281337** [comment]
Your oldTimestamp value exceeds the initial time and must pass 0 and update subsequent values ​​in the database and pass them already
