### ISSUE TITLE
Is it possible to install directly in FTP directory, ie. without using composer?

### ISSUE THREAD

**Issue by Ariel-International** [antonioribeiro/google2fa#190]
I would like to use this package on a shared server, I asked my provider but they are not answering.
What would be the steps to copy the library directly in a website and make it work?
Is it feasible at all?

**Comment by shusaura85** [comment]
It is possible, but you will need to include the [paragonie/constant_time_encoding](https://github.com/paragonie/constant_time_encoding) library as well.  
You will also need to either write an autoloader or manually include all the required files.  
  
In the long run, I recommend using composer.
