### ISSUE TITLE
Update 8.0.2 https://packagist.org/packages/pragmarx/google2fa#v8.0.2

### ISSUE THREAD

**Issue by curkan** [antonioribeiro/google2fa#212]
For some reason 8.0.2 on pacajist dated 2024-07-13 11:36 UTC
You have a new tag https://github.com/antonioribeiro/google2fa/releases/tag/v8.0.2 a few hours ago made, 

update the tag to https://packagist.org/packages/pragmarx/google2fa#v8.0.2 so that we get the error gone

PHP Parse error: syntax error, unexpected ‘)
', expecting variable (T_VARIABLE) in /vendor/pragmarx/google2fa/src/Google2FA.php on line 397

**Comment by antonioribeiro** [comment]
Somehow the commits where missing, retagged as 8.0.3. Thanks for reporting it!
