### ISSUE TITLE
Generated secret key isn't cryptographically secure 

### ISSUE THREAD

**Issue by aik099** [antonioribeiro/google2fa#24]
The `Google2FA::generateSecretKey` method internally uses `Google2FA::getRandomNumber`, which uses `mt_rand` function. According to its documentation (see http://php.net/mt_rand) it should not be used in security-related contexts.

Since current usage exactly qualifies as security related context I'm proposing to:

1. use https://packagist.org/packages/paragonie/random_compat package to get `random_int` function, that was added only in PHP 7
2. use `random_int` instead of `mt_rand`

If you're interested I can send a PR.

**Comment by base-zero** [comment]
👍

**Comment by overint** [comment]
This should definitely be changed. @aik099 did you create a pull request?

**Comment by aik099** [comment]
I haven't yet. If you'd like I can create it this week.

**Comment by aik099** [comment]
PR created and ready for review.
