### ISSUE TITLE
Drop "Str" class in favor of "symfony/polyfill-php56" package

### ISSUE THREAD

**Issue by aik099** [antonioribeiro/google2fa#26]
The https://packagist.org/packages/symfony/polyfill-php56 package provides `hash_equals` function (when it's missing only) and therefore:

* the `hash_equals(...)` can be used instead of `Str::equals(...)`
* the whole `Str` class can be dropped, because it's only consists of that `equals` function

**Comment by base-zero** [comment]
👍

**Comment by aik099** [comment]
PR created, ready for review.
