### ISSUE TITLE
[Laravel] Use Form validator for checking form

### ISSUE THREAD

**Issue by syphernl** [antonioribeiro/google2fa#4]
It would be nice if we could use the Laravel form validator to check whether the given token code is valid.

**Comment by jbrooksuk** [comment]
Write your own validation class instead?

**Comment by indiealexh** [comment]
There is little point of it being included in the package and would just add unnecessary bloat. Its easy enough to create this in laravel yourself.

**Comment by antonioribeiro** [comment]
I agree with both @jbrooksuk and @indiealexh, sorry. Maybe decoupling this package from Laravel and creating a new one to only support Laravel it could make sense, I don't know...
