### ISSUE TITLE
Using a bigger key results in "Invalid barcode"

### ISSUE THREAD

**Issue by rdev5** [antonioribeiro/google2fa#40]
FYI: https://github.com/antonioribeiro/google2fa#use-a-bigger-key

Setting a 32-byte key (with prefix) results in an `Invalid barcode` error in the Google Authenticator app whereas 16-byte key seems to work fine.

**Comment by antonioribeiro** [comment]
Not getting any errors, here. Just generated a pretty big prefixed key:

```
    private $keySize = 128;

    private $keyPrefix = 'this-is-a-prefix';
```

This is the generated (154 chars) key:

```
ORUGS4ZNNFZS2YJNOBZGKZTJPANZZ2IKXBYRBCZBPECH5T6WF3UL7X4X2N77KNGYA34EQ3DCHJ5MT3SP7TK7N5742QI4Y4ODHOMAZ4AEQZT2WV7GHAS6R4B7DTC7YUVNMQX63WBHBVYKQ6WMTK52S6E246
```

Look at the key and QRCode:

![image](https://cloud.githubusercontent.com/assets/3182864/17229534/60f5746e-54ee-11e6-9615-fe686ddf3c16.png)

**Comment by rdev5** [comment]
Have you tried in *in the Google Authenticator app* itself? That's what is generating the error.

**Comment by antonioribeiro** [comment]
I can confirm that, but looks like this is a Google Authenticator "feature": secrect key size has to be a power of 2, so, for instance a 512 bytes key worked here, but not 511.

But Authenticator on iOS worked (read the barcode and generated codes correctly) fine with all sizes and prefixes I tried, for instance:

    private $keySize = 137;

    private $keyPrefix = '7H6J5KL4';

So, as Google Authenticator is probably a standard for Google 2FA, I was thinking about creating a property (and a setter) to enforce compatibility and raise an exception on incompatible keys.

    /**
     * Enforce Google Authenticator Compatibility.
     */
    private $enforceGoogleAuthenticatorCompatibility = true;

What do you think?

**Comment by rdev5** [comment]
Sounds good. I would probably suggest having it enabled by default since this project is altogether **google**2fa and not just a generic otp library.

**Comment by antonioribeiro** [comment]
Changes are here: https://github.com/antonioribeiro/google2fa/commit/69bbda5b719941156ed8853972214e05fa5853b9. Anyone willing to test it?

**Comment by JC5** [comment]
So, nearly a year later, I tested it and it works fine for me!

**Comment by antonioribeiro** [comment]
@JC5, Thank you!
