### ISSUE TITLE
Use a more secure Base32 encoding algorithm 

### ISSUE THREAD

**Issue by cwt137** [antonioribeiro/google2fa#41]
Please use the paragonie/constant_time_encoding Composer package for doing Base32 encoding. It helps to prevent cache-timing attacks.

**Comment by aik099** [comment]
@cwt137 , please explain how base32 operations can be used to compromise library?

**Comment by aik099** [comment]
Currently base32 is used to generate 5 OTP codes, that are compared with user provided OTP code using `hash_equals` (timing attack safe) function. If I'm not mistaken, then time how long it takes to generate these 5 OTP codes can't be used to perform Timing Attack (I guess that's what you're worried about).

**Comment by cwt137** [comment]
It is the generation of the secret key that is susceptible to a trimming attack and should use constant time base32 encoding

**Comment by antonioribeiro** [comment]
Done. 
Sorry for the huge delay.
Thank you!
