### ISSUE TITLE
Wrong php version requirement

### ISSUE THREAD

**Issue by magroski** [antonioribeiro/google2fa#44]
Google2FA.php, line 276 calls the function random_int(), a PHP 7 function...

http://php.net/manual/en/function.random-int.php

But the project is flagged as PHP 5.4+ compliant

**Comment by aik099** [comment]
This is not a problem, because function is created by a https://github.com/paragonie/random_compat polyfill package.

**Comment by magroski** [comment]
Yup, it was my mistake. My autoloader silently failed to load random_compat.
