### ISSUE TITLE
QR Code scan not working

### ISSUE THREAD

**Issue by akki25** [antonioribeiro/google2fa#45]
I just added the package to my laravel application and the QR code is displaying correctly.
But when i scan the code it gives me url instead of OTP without any otp.
Infact when i scan the QR code on this page https://antoniocarlosribeiro.com/technology/google2fa it also gives me url without any otp.

Do we need any specific scan app to scan this QR??

**Comment by akki25** [comment]
I am not sure about what u want to say but do we need to make some more configuration elsewhere other than adding package to laravel , i mean ant google key or something??

**Comment by akki25** [comment]
OK thanks mate.

**Comment by aik099** [comment]
If the issue was solved for you, then please also close the issue on GitHub.
