### ISSUE TITLE
problem with KEY_REGENERATION 

### ISSUE THREAD

**Issue by parnus01** [antonioribeiro/google2fa#47]
i change value from 30second such as 25,45  to reduce lifetime of generate code but it not work

help me please i am newbie for google2FA

**Comment by aik099** [comment]
It did work, but we're checking 2 codes before and 2 codes after matching one to compensate for network delay between user submitting the form and time, when it reaches the server.

**Comment by parnus01** [comment]
ok but i have another question , when is verify code and it valid,after that i use same code and it can verify too how can i customize for one verify for one code

**Comment by aik099** [comment]
Same code can be used any number of times, until it's expired (30 seconds by default). This is how algorithm (not specific to this library).

You can configure window size (how much code before/after this one are checked) via `$window` parameter, when calling `verifyKey` method (see https://github.com/antonioribeiro/google2fa/blob/master/src/Google2FA.php#L212) as well.

**Comment by parnus01** [comment]
until it's expired (30 seconds by default) why after that i can used i timer around 2 minute

**Comment by aik099** [comment]
The problem you describe does happen on demo page https://antoniocarlosribeiro.com/technology/google2fa as well?

**Comment by parnus01** [comment]
yes you can try after 30 minute it can used

**Comment by parnus01** [comment]
and i dont know if i channge $window  What will  be change ?

**Comment by aik099** [comment]
> yes you can try after 30 minute it can used

If generated code is valid past it's expiration time, then it's surely a bug.

> and i dont know if i channge $window What will be change ?

Then your code won't be considered valid if all of these criteria are met:

* your code is valid for 30 seconds
* you submit code on 29th second of code validity
* http request reaches web server only after 2 seconds

I think window of `1` is enough to compensate for this. That would allow code to be valid for 3x it's expiration.

**Comment by parnus01** [comment]
very confuse after i change KEY_REGENERATION to 45 60 seconds it can't verify although code just generate

**Comment by sokai** [comment]
#23 "[Q] keyRegeneration period and window (key)" was the same intention …

**Comment by parnus01** [comment]
i can't change keyRegeneration by 30 right ?

**Comment by antonioribeiro** [comment]
Unless you can control the lifetime of your keys in the app your users will use to check the keys (Google Authenticator?), you should never touch key regeneration, those 30 seconds of lifetime for a key are used worldwide.

If you need the password to be available for a little more time, you have to play with `window`.

I have built a new playground page to help you with this: https://pragmarx.com/google2fa
