### ISSUE TITLE
Return type of getTimestamp()

### ISSUE THREAD

**Issue by SebastianS90** [antonioribeiro/google2fa#51]
The return type of `getTimestamp` is [specified](https://github.com/antonioribeiro/google2fa/blob/ac2b66265d5fda38ce097782d47089bc3366683d/src/Contracts/Google2FA.php#L20) to be `int`.
But the value returned is the [result from floor](https://github.com/antonioribeiro/google2fa/blob/ac2b66265d5fda38ce097782d47089bc3366683d/src/Google2FA.php#L122), and that is `float` (see [documentation](http://php.net/manual/en/function.floor.php#refsect1-function.floor-returnvalues)).

You even [test that the value is a float](https://github.com/antonioribeiro/google2fa/blob/ac2b66265d5fda38ce097782d47089bc3366683d/tests/spec/Google2FASpec.php#L102).

Can we make that consistent, please?
- Return `int`
  - Insert a cast to `int` in `getTimestamp`
  - Adjust the test to check `is_int`
- Return `float`
  - Fix `@return` annotation in interface and class

I can do a pull request for either choice if you tell me which way to go. In my opinion, `int` is better here because the value is floored anyways and even a 32 bit signed integer for a unix timestamp _divided by 30_ will be enough for almost another 2000 years - and by that time everyone should have switched to a system aware of 64 bit integers :smile:

**Comment by aik099** [comment]
👍  for adding `(int)` before returning value. Thanks to dynamic casting in PHP this was never a problem.

**Comment by antonioribeiro** [comment]
Moved it all to (int).
Thank you!
