### ISSUE TITLE
"Invalid token barcode" on IOS google authenticator app.

### ISSUE THREAD

**Issue by Deno028** [antonioribeiro/google2fa#54]
The lib work well on Android app but IOS.

Whatever I tried to change the keylength when I scan with my IPhone the error always appear: Invalid token barcode.

**Comment by aik099** [comment]
Are you using Google Authenticator app on iPhone as well?

With the Google Authenticator app I'm afraid you have to use default key length.

**Comment by antonioribeiro** [comment]
Did you set `setEnforceGoogleAuthenticatorCompatibility` to false? This enforcement was coded exactly because of this problem.

**Comment by lucaq** [comment]
Because there's an equal sign in the back of the string, and I just delete the equal sign, that's my method.
