### ISSUE TITLE
Company name & Holder name with spaces

### ISSUE THREAD

**Issue by david-vde** [antonioribeiro/google2fa#55]
Hi have a bug when using spaces in company name or holder.

I seen that this issue is fixed but not yet released.

After analysing your fix, I can see that you made a rawurlencode on company but not holder name. Why is that? The holder name can also have spaces.

See: https://github.com/antonioribeiro/google2fa/blob/master/src/Google2FA.php#L311

Thanks

**Comment by antonioribeiro** [comment]
Will be present in the next version.
