### ISSUE TITLE
Adding any prefix generates an unusable secret

### ISSUE THREAD

**Issue by melvinchia** [antonioribeiro/google2fa#57]
When I tried using no prefix:
`$otp_secret = $google2fa->generateSecretKey(16);`
It generates a usable secret, tested by Authy on iOS (manually key in the secret, or QR code scan)

When I tried using a blank prefix:
`$otp_secret = $google2fa->generateSecretKey(16, '');`
It generates a usable secret, tested by Authy on iOS (manually key in the secret, or QR code scan)

When I add a prefix prefix:
`$otp_secret = $google2fa->generateSecretKey(16, 'm');`
`$otp_secret = $google2fa->generateSecretKey(16, 'mel');`
`$otp_secret = $google2fa->generateSecretKey(16, 'melvin');`
All 3 lines yield an error, whether manually keying in the secret, or QR code scan.

Anybody else encounter this problem?

**Comment by milanjk** [comment]
I believe if we subtract the length of the prefix here it may fix the issue... haven't tested it myself yet:
`
    public function generateSecretKey($length = 16, $prefix = '')
    {
        $b32 = '234567QWERTYUIOPASDFGHJKLZXCVBNM';
        $secret = $prefix ? $this->toBase32($prefix) : '';
        $length = $prefix? ($length - count($prefix)):$length;
        for ($i = 0; $i < $length; $i++) {
            $secret .= $b32[$this->getRandomNumber()];
        }
        $this->validateSecret($secret);
        return $secret;
    }`

**Comment by JC5** [comment]
Yes, but this is a problem I only encounter on iOS.

https://github.com/firefly-iii/firefly-iii/issues/624

**Comment by melvinchia** [comment]
Strange, I received a suggestion thru email, but I don't see it on Github.
Is there a reason why it didn't appear?


In God's Love and Peace,
Melvin Chia

**Comment by melvinchia** [comment]
What puzzles me is, there's also a way to generate a "more secure" secret key using:
$otp_secret = $google2fa->generateSecretKey(32);

So is it that what is passed in "must add up to 16 or 32 characters", or does subtracting number of letters in the prefix from the number passed to the generateSecretKey function matter in this case?

**Comment by melvinchia** [comment]
@antonioribeiro , just to clarify, the purpose of the following (sub)function:

$secretKey = $google2fa->generateSecretKey(16, $userId);

Was documented as "prefixing the secret key", whereby a $userId is provided to the function, which would use the $userId to prefix the salt to generate a 16-bit key. Similarly if 32 is used, the purpose of the $userId is to prefix the salt to generate the key.

Now the explanation seems to be that I have to provide a 16/32-character (padded or full length) $userId which becomes the salt, instead of merely being just a prefix (original intention to increase security)? Am I understanding the explanation wrong here?

**Comment by antonioribeiro** [comment]
@melvinchia, I just rewrote that part, trying to make it more clear:

_You may prefix your secret keys, but you have to understand that, as your secret key must have length in power of 2, your prefix will have to have a complementary size. So if your key is 16 bytes long, if you add a prefix it must be also 16 bytes long, but as your prefixes will be converted to base 32, the max length of your prefix is 10 bytes. So, those are the sizes you can use in your prefixes:_

```
1, 2, 5, 10, 20, 40, 80...
```

_And it can be used like so:_

```php
$prefix = strpad($userId, 10, 'X');

$secretKey = $google2fa->generateSecretKey(16, $prefix);
```

I've also made a demo site for it: https://pragmarx.com/google2fa.
