### ISSUE TITLE
Not found class PragmaRX\Google2FA\Google2FA

### ISSUE THREAD

**Issue by sozonets** [antonioribeiro/google2fa#58]
```
use PragmaRX\Google2FA\Google2FA;

        $gFA = new Google2FA();

        $imageDataUri = $gFA->getQRCodeInline(
            $request->getHttpHost(),
            $user->email,
            $secret,
            200
        );
```
Class 'PragmaRX\Google2FA\Google2FA' not found
How to fix for Laravel 5.3 ?

**Comment by yurik94** [comment]
How did you fix? same error :(

**Comment by sozonets** [comment]
`composer update` fix it
or 
Completely reload the entire project on your server

**Comment by yurik94** [comment]
something has been changed in the repo name I suspect and in the namespaces:

Correct usage on the Laravel bridge (5.4), /config/app.php:

PragmaRX\Google2FALaravel\ServiceProvider::class,

'Google2FA' => PragmaRX\Google2FALaravel\Facade::class,

**Comment by antonioribeiro** [comment]
Sorry about that. That's basically why I tagged a new major. And the docs were wrong, I just fix this info in the bridge package.

**Comment by yurik94** [comment]
Nevermind, I've followed this

[https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/](https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/)

and I just finished the 2FA 👍 
Anyway there's something that should be updated on that tutorial but I can confirm it's working on 5.4.

P.S. I'm working on Php 7.1 and there are some non-static methods called statically 😄

**Comment by henriquepalazzo** [comment]
Getting the same error here with Laravel 5.5: Class pragmarx.google2fa does not exist. I already tried composer update and many other things, still not working.

**Comment by antonioribeiro** [comment]
@yurik94 , if you look at the class source: https://github.com/antonioribeiro/google2fa/blob/master/src/Google2FA.php, you'll see there are no static methods, so this must be a Laravel Facade thing or something you are doing.

**Comment by antonioribeiro** [comment]
@henriquepalazzo, I can confirm it works fine on Laravel 5.5. Usually this happens when the service provider was not registered. But you may be using the wrong package, this is the Laravel version of this package: https://github.com/antonioribeiro/google2fa-laravel
