### ISSUE TITLE
Old tokens are valid

### ISSUE THREAD

**Issue by ginomessmer** [antonioribeiro/google2fa#59]
Verifying old tokens which has been used minutes ago get validated. Is there some way to disable old keys?

**Comment by SebastianS90** [comment]
Have a look at #50. Maybe I should fork this project because no one seems to be interested in that important feature.

**Comment by ginomessmer** [comment]
Thanks for heads up. Probably worth to include it, it's a great and yet simple to integrate package though.

**Comment by lukepolo** [comment]
#50 has been merged! you probably can close this now.

**Comment by antonioribeiro** [comment]
You already had a way to disable them through `window`, you just have to set window to 1 or even 0: 

```
$isValid = $google2fa->verifyKey($secret, $password, 0);
```

What https://github.com/antonioribeiro/google2fa/pull/50 gives us is different: you now have the ability to disable passwords already used.
