### ISSUE TITLE
QR Codes not working in Laravel 5.4.

### ISSUE THREAD

**Issue by HackerFinn** [antonioribeiro/google2fa#60]
I keep getting invalid QR codes when using default settings on Laravel 5.4.
Here is my code:
`/**
     * Generate a new 2FA key.
     *
     * @return void
     */
    public function setup2FA(Google2FA $google2fa)
    {
        $user = Auth::user();
        $google2fa_secret = $google2fa->generateSecretKey();
        $google2fa_url = $google2fa->getQRCodeGoogleUrl(
            config('app.name', 'Laravel'),
            $user->email,
            $user->google2fa_secret
        );

        return view('2fa.setup', ['google2fa_secret' => $google2fa_secret, 'google2fa_url' => $google2fa_url]);
    }`
I should note that I am using the Microsoft Authenticator app on Windows 10 mobile, but my coworker is having the same issue using Google Authenticator on Android.
Also the Secrets themselves work just fine, if entered manually.
What gives?

**Comment by tonydew** [comment]
I'm using this in a brand new test 5.4 projects and it's generating both the `getQRCodeGoogleUrl()` and `getQRCodeInline()` QR codes. Of course, to use the latter, you need to `composer require "bacon/bacon-qr-code":"~1.0"` too.

**Comment by HackerFinn** [comment]
I figured it out. My mistake. I was tired and missed an error in my code above.
And as you can see from above, I used the Google url variant, and it did generate it just fine.
I just didn't give it the actual secret, because of a mistake in my code.
Closing this issue now.
