### ISSUE TITLE
Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found without providers exist

### ISSUE THREAD

**Issue by ldt1992** [antonioribeiro/google2fa#87]
Please help me, I have added provider 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' and 'Google2FA' => PragmaRX\Google2FA\Vendor\Laravel\Facade::class in alias, but I get this error. I have to tried with "composer update, composer install, php artisan vendor:publish" but it 's not fixed.

**Comment by antonioribeiro** [comment]
This is the PHP (agnostic) repository, Laravel has its [own repo](https://github.com/antonioribeiro/google2fa-laravel). And you should use probably be using:

``` php
PragmaRX\Google2FALaravel\ServiceProvider::class,

'Google2FA' => PragmaRX\Google2FALaravel\Facade::class,
```
