### ISSUE TITLE
Recovery Codes Question

### ISSUE THREAD

**Issue by codivist** [antonioribeiro/google2fa#9]
Thanks for the awesome work on this! I've implemented this package into Laravel and it works great!

I'm now trying to generate recover codes or back up codes. Like this page: https://support.google.com/accounts/answer/1187538?hl=en
How are you generating recovery codes (backup codes) incase a user doesn't have their phone?

I've looked through the code and have been thinking of different ways I can implement a recovery code list, but coming up empty handed.  

Can the one time password method `oathHotp` be used in a loop to generate those codes?

**Comment by danlake** [comment]
I have run into exactly the same issue. Would be useful to understand how to implement this as not all TFA apps / clients can scan QR codes

**Comment by aik099** [comment]
The recovery codes are one time use passwords, that are:

* generated not based on time
* expire immediately after use

This library isn't responsible for creating/validating them. You can use any secure random generator for creating these codes.

**Comment by GrahamCampbell** [comment]
This can probably closed. This is outside the scope of this package.

**Comment by antonioribeiro** [comment]
As @GrahamCampbell said, not related to this package. You should generate recovery codes on your app using a different method (sms, email...), and it must not be based on time as this package is.
