### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by binitghetiya** [antonioribeiro/google2fa#90]
Laravel 5.4 Php 5.6

$user = User::first();
$google2fa = new Google2FA();
$code_from_app = "332117";

$valid = $google2fa->verifyKey($user->google2fa_secret, $code_from_app);

Throwing error : **_Default value for parameters with a class type hint can only be NULL_**

![selection_080](https://user-images.githubusercontent.com/14307119/33868830-58ac2320-df2b-11e7-94a2-88afe2baead4.png)

I had some search and found that php-cs-fixer issue it requires PHP 7.1  but i haven't used that and for this library min PHP version require is 5.4 So, please look into this issue.

Thanks

**Comment by visualarte** [comment]
Any update on this? I have the same problem but working locally with php  v5.6.25 work perfect but on production server, same php version I get the same error:


(1/1) FatalErrorExceptionDefault value for parameters with a class type hint can only be NULL
--
in Base32.php (line 43)

I'm using laravel 5.4...

**Comment by antonioribeiro** [comment]
I need more information on this, because there are no type hints, code has 100% tests coverage and is passing even on PHP 5.4:

![image](https://user-images.githubusercontent.com/3182864/37110875-ec511034-221c-11e8-9188-dfd2545852ea.png)

**Comment by themirage500** [comment]
Got this error too :  Default value for parameters with a class type hint can only be NULL in vendor\paragonie\constant_time_encoding\src\Base32.php on line 43
PHP 5.5

Anyone got a fix ?
