### ISSUE TITLE
random_int only php7

### ISSUE THREAD

**Issue by shigella** [antonioribeiro/google2fa#91]
you mention it is compatible with php 5.4 but the function random_int in base32 trait is only available in php7 and will return an error message

**Comment by GrahamCampbell** [comment]
https://github.com/antonioribeiro/google2fa/blob/master/composer.json#L16

**Comment by antonioribeiro** [comment]
As @GrahamCampbell noted, it is compatible via random_compat, and [tests are passing](https://travis-ci.org/antonioribeiro/google2fa) from PHP 5.4 to 7.2:

![image](https://user-images.githubusercontent.com/3182864/34640017-516117aa-f2d2-11e7-8380-03d8bc50b682.png)
