### ISSUE TITLE
$secret = $request->input('secret'); not found

### ISSUE THREAD

**Issue by JordyKroeze** [antonioribeiro/google2fa#92]
Hello,

When i follow the readme i get a QRcode and everyting.

But i get this error if i try to check the code.

Notice: Undefined variable: request in FILENAME on line 30

Fatal error: Call to a member function input() on a non-object in FILENAME on line 30

Line 30 is this (Changed my secretkey)
$secret = $request->input('abcdef');

Where is this request variable coming from ?

**Comment by JordyKroeze** [comment]
Nevermind, found it.
You have to get the key they enter there.

**Comment by edgren** [comment]
I have the same problem. Even if I have entered the TOTP from Authenticator Plus after I scanned the QR code, it only generate `Uncaught Error: Call to a member function input() on null in ...`. Why?

Here's is my current code:
```
$secretkey = $_POST['textfield-verify-code'];    # This is the input that the user enters theirs TOTP
$secret = $request->input($secretkey);
$window = 8;
$valid = $google2fa->verifyKey($user->google2fa_secret, $secret, $window);
echo $valid;
```
