### ISSUE TITLE
Google 2FA Enable and Disable working perfectly but One time Password not working. in laravel 5.5

### ISSUE THREAD

**Issue by rinkesh-prajapat** [antonioribeiro/google2fa#93]
I have use package 
 composer require pragmarx/google2fa-laravel
composer require bacon/bacon-qr-code
and my reference url is - https://www.5balloons.info/two-factor-authentication-google2fa-laravel-5/

**Comment by antonioribeiro** [comment]
We need more information: what are you doing? what's not working? You are also not using the correct repository to report this, you should be using https://github.com/antonioribeiro/google2fa-laravel, so I'm closing it here.
