### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by remicollet** [antonioribeiro/google2fa#95]
While composer.json states "BSD-3-Clause" (as the LICENSE file), the file header states "GPLv3+"

Can you please clarify ?

**Comment by antonioribeiro** [comment]
I was probably using and old package template. Moved it all to MIT. Thanks for reporting.

**Comment by remicollet** [comment]
Nah, the problem is that the Google2FA.php states it is GPLv3

And you cannot re-license an original GPLv3 work unders MIT or BSD

**Comment by antonioribeiro** [comment]
So, fixed: https://github.com/antonioribeiro/google2fa/blob/master/LICENSE.md.
Thank you.

**Comment by antonioribeiro** [comment]
Relicensed to MIT as per https://github.com/antonioribeiro/google2fa/issues/100.
