### ISSUE TITLE
Catalyst Sentinel Support

### ISSUE THREAD

**Issue by webstudiozimbabwe** [antonioribeiro/google2fa#99]
Hello, can you add support for Laravel Catalyst Sentinel for the middleware

**Comment by antonioribeiro** [comment]
First of all, you are probably looking for the Laravel version of this package: https://github.com/antonioribeiro/google2fa-laravel

And, how would that support be? Curently, in Laravel, you can easily write new middlewares, so I'm also not sure if the package should cover all Auth packages around, and Sentinel is one in one hundred.

If you still have questions or input, please open an issue in the proper package repository.
